// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inventory.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	protos "github.com/michaelhenkel/dmng/devicemanager/protos"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Device struct {
	Name                 string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Interfaces           []*protos.Interface `protobuf:"bytes,2,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	Role                 *Role               `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_7173caedb7c6ae96, []int{0}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Device) GetInterfaces() []*protos.Interface {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

func (m *Device) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

type Role struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_7173caedb7c6ae96, []int{1}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Result struct {
	Received             bool     `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	Applied              bool     `protobuf:"varint,2,opt,name=applied,proto3" json:"applied,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_7173caedb7c6ae96, []int{2}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetReceived() bool {
	if m != nil {
		return m.Received
	}
	return false
}

func (m *Result) GetApplied() bool {
	if m != nil {
		return m.Applied
	}
	return false
}

func (m *Result) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Filter struct {
	Role                 *Role    `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_7173caedb7c6ae96, []int{3}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

func init() {
	proto.RegisterType((*Device)(nil), "inventory.Device")
	proto.RegisterType((*Role)(nil), "inventory.Role")
	proto.RegisterType((*Result)(nil), "inventory.Result")
	proto.RegisterType((*Filter)(nil), "inventory.Filter")
}

func init() { proto.RegisterFile("inventory.proto", fileDescriptor_7173caedb7c6ae96) }

var fileDescriptor_7173caedb7c6ae96 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x4d, 0x5b, 0x62, 0x33, 0x15, 0xaa, 0x7b, 0x0a, 0x39, 0x95, 0x78, 0xa9, 0x07, 0x93,
	0xd2, 0x1e, 0xec, 0x59, 0x8b, 0x52, 0xf0, 0x20, 0x7b, 0xf4, 0x22, 0xdb, 0x64, 0x4c, 0x17, 0x37,
	0x9b, 0xb2, 0xbb, 0x0d, 0x88, 0x9f, 0xd9, 0xef, 0x20, 0xdd, 0xfc, 0xb1, 0xc5, 0x22, 0x7a, 0xca,
	0xcc, 0x7b, 0xf3, 0xcb, 0x3c, 0x86, 0x85, 0x21, 0x97, 0x25, 0x4a, 0x53, 0xa8, 0xf7, 0x68, 0xa3,
	0x0a, 0x53, 0x10, 0xaf, 0x15, 0x82, 0xab, 0x14, 0x4b, 0x9e, 0x60, 0xce, 0x24, 0xcb, 0x50, 0xc5,
	0xd6, 0xd7, 0x71, 0x25, 0xbe, 0xd4, 0x6a, 0x45, 0x85, 0x1f, 0xe0, 0x2e, 0xac, 0x4e, 0x08, 0xf4,
	0x24, 0xcb, 0xd1, 0x77, 0x46, 0xce, 0xd8, 0xa3, 0xb6, 0x26, 0x73, 0x00, 0x2e, 0x0d, 0xaa, 0x57,
	0x96, 0xa0, 0xf6, 0x3b, 0xa3, 0xee, 0x78, 0x30, 0xf5, 0xa3, 0x83, 0xbf, 0x47, 0xcb, 0x66, 0x80,
	0xee, 0xcd, 0x92, 0x4b, 0xe8, 0xa9, 0x42, 0xa0, 0xdf, 0x1d, 0x39, 0xe3, 0xc1, 0x74, 0x18, 0x7d,
	0xa7, 0xa5, 0x85, 0x40, 0x6a, 0xcd, 0x30, 0x80, 0xde, 0xae, 0x3b, 0xb6, 0x3a, 0x7c, 0x02, 0x97,
	0xa2, 0xde, 0x0a, 0x43, 0x02, 0xe8, 0x2b, 0x4c, 0x90, 0x97, 0x98, 0xda, 0x89, 0x3e, 0x6d, 0x7b,
	0xe2, 0xc3, 0x29, 0xdb, 0x6c, 0x04, 0xc7, 0xd4, 0xef, 0x58, 0xab, 0x69, 0xc9, 0x39, 0x74, 0x73,
	0x9d, 0xd9, 0xfd, 0x1e, 0xdd, 0x95, 0xe1, 0x35, 0xb8, 0xf7, 0x5c, 0x18, 0x54, 0x6d, 0x38, 0xe7,
	0x97, 0x70, 0xd3, 0x4f, 0x07, 0xbc, 0x65, 0x63, 0x90, 0x19, 0x78, 0x0f, 0x68, 0xea, 0x53, 0x5d,
	0xec, 0x11, 0x95, 0x14, 0xfc, 0x94, 0xc2, 0x13, 0x72, 0x03, 0x83, 0x47, 0xae, 0x6b, 0x4a, 0x1f,
	0x60, 0x55, 0x92, 0xa3, 0xd8, 0xc4, 0x21, 0x73, 0x38, 0xbb, 0x53, 0xc8, 0x0c, 0xfe, 0x6d, 0x61,
	0x75, 0xa8, 0x86, 0x5c, 0xa0, 0xc0, 0xff, 0x93, 0xb7, 0x93, 0xe7, 0x28, 0xe3, 0x66, 0xbd, 0x5d,
	0x45, 0x49, 0x91, 0xc7, 0x39, 0x4f, 0xd6, 0x0c, 0xc5, 0x1a, 0xe5, 0x1b, 0x8a, 0x38, 0xcd, 0x65,
	0x16, 0xb7, 0x54, 0xfd, 0xa0, 0x56, 0xae, 0xfd, 0xce, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x36,
	0xba, 0xa2, 0xc2, 0x8b, 0x02, 0x00, 0x00,
}
