// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fabric_manager.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	// Types that are valid to be assigned to Request:
	//	*Request_Create
	//	*Request_Delete
	Request              isRequest_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b2897b7f8db28e9, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type isRequest_Request interface {
	isRequest_Request()
}

type Request_Create struct {
	Create *Create `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type Request_Delete struct {
	Delete *Delete `protobuf:"bytes,2,opt,name=delete,proto3,oneof"`
}

func (*Request_Create) isRequest_Request() {}

func (*Request_Delete) isRequest_Request() {}

func (m *Request) GetRequest() isRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Request) GetCreate() *Create {
	if x, ok := m.GetRequest().(*Request_Create); ok {
		return x.Create
	}
	return nil
}

func (m *Request) GetDelete() *Delete {
	if x, ok := m.GetRequest().(*Request_Delete); ok {
		return x.Delete
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Request) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Request_Create)(nil),
		(*Request_Delete)(nil),
	}
}

type Create struct {
	// Types that are valid to be assigned to CreateRequest:
	//	*Create_Fabric
	CreateRequest        isCreate_CreateRequest `protobuf_oneof:"create_request"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Create) Reset()         { *m = Create{} }
func (m *Create) String() string { return proto.CompactTextString(m) }
func (*Create) ProtoMessage()    {}
func (*Create) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b2897b7f8db28e9, []int{1}
}

func (m *Create) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Create.Unmarshal(m, b)
}
func (m *Create) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Create.Marshal(b, m, deterministic)
}
func (m *Create) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Create.Merge(m, src)
}
func (m *Create) XXX_Size() int {
	return xxx_messageInfo_Create.Size(m)
}
func (m *Create) XXX_DiscardUnknown() {
	xxx_messageInfo_Create.DiscardUnknown(m)
}

var xxx_messageInfo_Create proto.InternalMessageInfo

type isCreate_CreateRequest interface {
	isCreate_CreateRequest()
}

type Create_Fabric struct {
	Fabric *Fabric `protobuf:"bytes,1,opt,name=fabric,proto3,oneof"`
}

func (*Create_Fabric) isCreate_CreateRequest() {}

func (m *Create) GetCreateRequest() isCreate_CreateRequest {
	if m != nil {
		return m.CreateRequest
	}
	return nil
}

func (m *Create) GetFabric() *Fabric {
	if x, ok := m.GetCreateRequest().(*Create_Fabric); ok {
		return x.Fabric
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Create) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Create_Fabric)(nil),
	}
}

type Fabric struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Devices              []string `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fabric) Reset()         { *m = Fabric{} }
func (m *Fabric) String() string { return proto.CompactTextString(m) }
func (*Fabric) ProtoMessage()    {}
func (*Fabric) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b2897b7f8db28e9, []int{2}
}

func (m *Fabric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fabric.Unmarshal(m, b)
}
func (m *Fabric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fabric.Marshal(b, m, deterministic)
}
func (m *Fabric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fabric.Merge(m, src)
}
func (m *Fabric) XXX_Size() int {
	return xxx_messageInfo_Fabric.Size(m)
}
func (m *Fabric) XXX_DiscardUnknown() {
	xxx_messageInfo_Fabric.DiscardUnknown(m)
}

var xxx_messageInfo_Fabric proto.InternalMessageInfo

func (m *Fabric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Fabric) GetDevices() []string {
	if m != nil {
		return m.Devices
	}
	return nil
}

type Delete struct {
	// Types that are valid to be assigned to DeleteRequest:
	//	*Delete_Fabrics
	DeleteRequest        isDelete_DeleteRequest `protobuf_oneof:"delete_request"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Delete) Reset()         { *m = Delete{} }
func (m *Delete) String() string { return proto.CompactTextString(m) }
func (*Delete) ProtoMessage()    {}
func (*Delete) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b2897b7f8db28e9, []int{3}
}

func (m *Delete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delete.Unmarshal(m, b)
}
func (m *Delete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delete.Marshal(b, m, deterministic)
}
func (m *Delete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delete.Merge(m, src)
}
func (m *Delete) XXX_Size() int {
	return xxx_messageInfo_Delete.Size(m)
}
func (m *Delete) XXX_DiscardUnknown() {
	xxx_messageInfo_Delete.DiscardUnknown(m)
}

var xxx_messageInfo_Delete proto.InternalMessageInfo

type isDelete_DeleteRequest interface {
	isDelete_DeleteRequest()
}

type Delete_Fabrics struct {
	Fabrics string `protobuf:"bytes,1,opt,name=fabrics,proto3,oneof"`
}

func (*Delete_Fabrics) isDelete_DeleteRequest() {}

func (m *Delete) GetDeleteRequest() isDelete_DeleteRequest {
	if m != nil {
		return m.DeleteRequest
	}
	return nil
}

func (m *Delete) GetFabrics() string {
	if x, ok := m.GetDeleteRequest().(*Delete_Fabrics); ok {
		return x.Fabrics
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Delete) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Delete_Fabrics)(nil),
	}
}

type Result struct {
	Received             bool     `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	Applied              bool     `protobuf:"varint,2,opt,name=applied,proto3" json:"applied,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Success              bool     `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b2897b7f8db28e9, []int{4}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetReceived() bool {
	if m != nil {
		return m.Received
	}
	return false
}

func (m *Result) GetApplied() bool {
	if m != nil {
		return m.Applied
	}
	return false
}

func (m *Result) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Result) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Request)(nil), "fabricmanager.Request")
	proto.RegisterType((*Create)(nil), "fabricmanager.Create")
	proto.RegisterType((*Fabric)(nil), "fabricmanager.Fabric")
	proto.RegisterType((*Delete)(nil), "fabricmanager.Delete")
	proto.RegisterType((*Result)(nil), "fabricmanager.Result")
}

func init() { proto.RegisterFile("fabric_manager.proto", fileDescriptor_9b2897b7f8db28e9) }

var fileDescriptor_9b2897b7f8db28e9 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xcd, 0x6e, 0xf2, 0x30,
	0x10, 0x24, 0x80, 0x12, 0xd8, 0x4f, 0x20, 0x64, 0x7d, 0x54, 0x11, 0x27, 0xc4, 0x89, 0x53, 0x52,
	0xd1, 0xaa, 0x0f, 0x00, 0x6d, 0x85, 0x54, 0xf5, 0xe2, 0x43, 0x0f, 0xbd, 0x20, 0xe3, 0x6c, 0x43,
	0xda, 0x24, 0x50, 0xdb, 0xe1, 0xf9, 0x2b, 0x7b, 0x93, 0x48, 0xf4, 0xe7, 0x14, 0xef, 0xec, 0xcc,
	0xce, 0x78, 0x63, 0xf8, 0xff, 0x26, 0xf6, 0x2a, 0x93, 0xbb, 0x42, 0x94, 0x22, 0x45, 0x15, 0x9d,
	0xd4, 0xd1, 0x1c, 0xd9, 0x88, 0xd0, 0x1a, 0x5c, 0x9c, 0x21, 0xe0, 0xf8, 0x59, 0xa1, 0x36, 0x2c,
	0x06, 0x5f, 0x2a, 0x14, 0x06, 0x43, 0x6f, 0xee, 0x2d, 0xff, 0xad, 0xa6, 0xd1, 0x05, 0x35, 0xda,
	0xb8, 0xe6, 0xb6, 0xc3, 0x6b, 0x9a, 0x15, 0x24, 0x98, 0xa3, 0xc1, 0xb0, 0xfb, 0xab, 0xe0, 0xde,
	0x35, 0xad, 0x80, 0x68, 0xeb, 0x21, 0x04, 0x8a, 0xcc, 0x16, 0x4f, 0xe0, 0x6f, 0xda, 0x29, 0x24,
	0xfb, 0xc3, 0xf6, 0xd1, 0x55, 0x76, 0x0a, 0xe1, 0xeb, 0x09, 0x8c, 0x29, 0xc0, 0xae, 0x19, 0x76,
	0x07, 0x3e, 0xb1, 0x18, 0x83, 0x7e, 0x29, 0x0a, 0xba, 0xc1, 0x90, 0xbb, 0x33, 0x0b, 0x21, 0x48,
	0xf0, 0x9c, 0x49, 0xd4, 0x61, 0x77, 0xde, 0x5b, 0x0e, 0x79, 0x53, 0x5a, 0x1d, 0x65, 0x64, 0x33,
	0x08, 0x68, 0xba, 0x26, 0xe9, 0xb6, 0xc3, 0x1b, 0xc0, 0xfa, 0x51, 0xfe, 0xd6, 0xef, 0x1d, 0x7c,
	0x8e, 0xba, 0xca, 0x0d, 0x9b, 0xc1, 0x40, 0xa1, 0xc4, 0xec, 0x8c, 0x89, 0x13, 0x0e, 0x78, 0x5b,
	0x5b, 0x5f, 0x71, 0x3a, 0xe5, 0x19, 0x26, 0x6e, 0x3f, 0x03, 0xde, 0x94, 0x6c, 0x02, 0xbd, 0x42,
	0xa7, 0x61, 0xcf, 0x85, 0xb4, 0x47, 0xcb, 0xd5, 0x95, 0x94, 0xa8, 0x75, 0xd8, 0x27, 0x6e, 0x5d,
	0xae, 0x5e, 0x60, 0x44, 0x77, 0x7b, 0xa6, 0x7d, 0xb0, 0x07, 0x18, 0xd7, 0x7f, 0x6c, 0x2b, 0xca,
	0x24, 0x47, 0xc5, 0xae, 0xbe, 0x6d, 0xac, 0x6e, 0xcf, 0xa6, 0x3f, 0x70, 0x9b, 0x79, 0xd1, 0x59,
	0x7a, 0xd7, 0xde, 0xfa, 0xf6, 0x75, 0x95, 0x66, 0xe6, 0x50, 0xed, 0x23, 0x79, 0x2c, 0xe2, 0x22,
	0x93, 0x07, 0x81, 0xf9, 0x01, 0xcb, 0x0f, 0xcc, 0xe3, 0xa4, 0x28, 0xd3, 0xf8, 0x42, 0x1b, 0xbb,
	0xc7, 0xa3, 0xf7, 0xbe, 0xfb, 0xde, 0x7c, 0x05, 0x00, 0x00, 0xff, 0xff, 0x7a, 0xf4, 0x25, 0xc4,
	0x5c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FabricManagerClient is the client API for FabricManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FabricManagerClient interface {
	RequestHandler(ctx context.Context, opts ...grpc.CallOption) (FabricManager_RequestHandlerClient, error)
}

type fabricManagerClient struct {
	cc *grpc.ClientConn
}

func NewFabricManagerClient(cc *grpc.ClientConn) FabricManagerClient {
	return &fabricManagerClient{cc}
}

func (c *fabricManagerClient) RequestHandler(ctx context.Context, opts ...grpc.CallOption) (FabricManager_RequestHandlerClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FabricManager_serviceDesc.Streams[0], "/fabricmanager.FabricManager/RequestHandler", opts...)
	if err != nil {
		return nil, err
	}
	x := &fabricManagerRequestHandlerClient{stream}
	return x, nil
}

type FabricManager_RequestHandlerClient interface {
	Send(*Request) error
	Recv() (*Result, error)
	grpc.ClientStream
}

type fabricManagerRequestHandlerClient struct {
	grpc.ClientStream
}

func (x *fabricManagerRequestHandlerClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fabricManagerRequestHandlerClient) Recv() (*Result, error) {
	m := new(Result)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FabricManagerServer is the server API for FabricManager service.
type FabricManagerServer interface {
	RequestHandler(FabricManager_RequestHandlerServer) error
}

// UnimplementedFabricManagerServer can be embedded to have forward compatible implementations.
type UnimplementedFabricManagerServer struct {
}

func (*UnimplementedFabricManagerServer) RequestHandler(srv FabricManager_RequestHandlerServer) error {
	return status.Errorf(codes.Unimplemented, "method RequestHandler not implemented")
}

func RegisterFabricManagerServer(s *grpc.Server, srv FabricManagerServer) {
	s.RegisterService(&_FabricManager_serviceDesc, srv)
}

func _FabricManager_RequestHandler_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FabricManagerServer).RequestHandler(&fabricManagerRequestHandlerServer{stream})
}

type FabricManager_RequestHandlerServer interface {
	Send(*Result) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type fabricManagerRequestHandlerServer struct {
	grpc.ServerStream
}

func (x *fabricManagerRequestHandlerServer) Send(m *Result) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fabricManagerRequestHandlerServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _FabricManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fabricmanager.FabricManager",
	HandlerType: (*FabricManagerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RequestHandler",
			Handler:       _FabricManager_RequestHandler_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "fabric_manager.proto",
}
