// Code generated by protoc-gen-go. DO NOT EDIT.
// source: device_manager.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Interface struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ipv4                 string     `protobuf:"bytes,2,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6                 string     `protobuf:"bytes,3,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	Parent               *Interface `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
	Uuid                 string     `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Device               *Device    `protobuf:"bytes,6,opt,name=device,proto3" json:"device,omitempty"`
	Version              int32      `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Interface) Reset()         { *m = Interface{} }
func (m *Interface) String() string { return proto.CompactTextString(m) }
func (*Interface) ProtoMessage()    {}
func (*Interface) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcbdd1ffbcbe4fbb, []int{0}
}

func (m *Interface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interface.Unmarshal(m, b)
}
func (m *Interface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interface.Marshal(b, m, deterministic)
}
func (m *Interface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interface.Merge(m, src)
}
func (m *Interface) XXX_Size() int {
	return xxx_messageInfo_Interface.Size(m)
}
func (m *Interface) XXX_DiscardUnknown() {
	xxx_messageInfo_Interface.DiscardUnknown(m)
}

var xxx_messageInfo_Interface proto.InternalMessageInfo

func (m *Interface) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Interface) GetIpv4() string {
	if m != nil {
		return m.Ipv4
	}
	return ""
}

func (m *Interface) GetIpv6() string {
	if m != nil {
		return m.Ipv6
	}
	return ""
}

func (m *Interface) GetParent() *Interface {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *Interface) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Interface) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *Interface) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type Device struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcbdd1ffbcbe4fbb, []int{1}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Device) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type Result struct {
	Received             bool     `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	Applied              bool     `protobuf:"varint,2,opt,name=applied,proto3" json:"applied,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Success              bool     `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcbdd1ffbcbe4fbb, []int{2}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetReceived() bool {
	if m != nil {
		return m.Received
	}
	return false
}

func (m *Result) GetApplied() bool {
	if m != nil {
		return m.Applied
	}
	return false
}

func (m *Result) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Result) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Filter struct {
	Parent               *Interface `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcbdd1ffbcbe4fbb, []int{3}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetParent() *Interface {
	if m != nil {
		return m.Parent
	}
	return nil
}

type Process struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Process) Reset()         { *m = Process{} }
func (m *Process) String() string { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()    {}
func (*Process) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcbdd1ffbcbe4fbb, []int{4}
}

func (m *Process) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process.Unmarshal(m, b)
}
func (m *Process) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process.Marshal(b, m, deterministic)
}
func (m *Process) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process.Merge(m, src)
}
func (m *Process) XXX_Size() int {
	return xxx_messageInfo_Process.Size(m)
}
func (m *Process) XXX_DiscardUnknown() {
	xxx_messageInfo_Process.DiscardUnknown(m)
}

var xxx_messageInfo_Process proto.InternalMessageInfo

func (m *Process) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type Request struct {
	// Types that are valid to be assigned to Request:
	//	*Request_Create
	//	*Request_Delete
	Request              isRequest_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcbdd1ffbcbe4fbb, []int{5}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type isRequest_Request interface {
	isRequest_Request()
}

type Request_Create struct {
	Create *Create `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type Request_Delete struct {
	Delete *Delete `protobuf:"bytes,2,opt,name=delete,proto3,oneof"`
}

func (*Request_Create) isRequest_Request() {}

func (*Request_Delete) isRequest_Request() {}

func (m *Request) GetRequest() isRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Request) GetCreate() *Create {
	if x, ok := m.GetRequest().(*Request_Create); ok {
		return x.Create
	}
	return nil
}

func (m *Request) GetDelete() *Delete {
	if x, ok := m.GetRequest().(*Request_Delete); ok {
		return x.Delete
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Request) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Request_Create)(nil),
		(*Request_Delete)(nil),
	}
}

type Create struct {
	// Types that are valid to be assigned to CreateRequest:
	//	*Create_Interfaces
	CreateRequest        isCreate_CreateRequest `protobuf_oneof:"create_request"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Create) Reset()         { *m = Create{} }
func (m *Create) String() string { return proto.CompactTextString(m) }
func (*Create) ProtoMessage()    {}
func (*Create) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcbdd1ffbcbe4fbb, []int{6}
}

func (m *Create) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Create.Unmarshal(m, b)
}
func (m *Create) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Create.Marshal(b, m, deterministic)
}
func (m *Create) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Create.Merge(m, src)
}
func (m *Create) XXX_Size() int {
	return xxx_messageInfo_Create.Size(m)
}
func (m *Create) XXX_DiscardUnknown() {
	xxx_messageInfo_Create.DiscardUnknown(m)
}

var xxx_messageInfo_Create proto.InternalMessageInfo

type isCreate_CreateRequest interface {
	isCreate_CreateRequest()
}

type Create_Interfaces struct {
	Interfaces *Interfaces `protobuf:"bytes,1,opt,name=interfaces,proto3,oneof"`
}

func (*Create_Interfaces) isCreate_CreateRequest() {}

func (m *Create) GetCreateRequest() isCreate_CreateRequest {
	if m != nil {
		return m.CreateRequest
	}
	return nil
}

func (m *Create) GetInterfaces() *Interfaces {
	if x, ok := m.GetCreateRequest().(*Create_Interfaces); ok {
		return x.Interfaces
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Create) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Create_Interfaces)(nil),
	}
}

type Interfaces struct {
	Interface            []*Interface `protobuf:"bytes,1,rep,name=interface,proto3" json:"interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Interfaces) Reset()         { *m = Interfaces{} }
func (m *Interfaces) String() string { return proto.CompactTextString(m) }
func (*Interfaces) ProtoMessage()    {}
func (*Interfaces) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcbdd1ffbcbe4fbb, []int{7}
}

func (m *Interfaces) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interfaces.Unmarshal(m, b)
}
func (m *Interfaces) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interfaces.Marshal(b, m, deterministic)
}
func (m *Interfaces) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interfaces.Merge(m, src)
}
func (m *Interfaces) XXX_Size() int {
	return xxx_messageInfo_Interfaces.Size(m)
}
func (m *Interfaces) XXX_DiscardUnknown() {
	xxx_messageInfo_Interfaces.DiscardUnknown(m)
}

var xxx_messageInfo_Interfaces proto.InternalMessageInfo

func (m *Interfaces) GetInterface() []*Interface {
	if m != nil {
		return m.Interface
	}
	return nil
}

type Delete struct {
	// Types that are valid to be assigned to DeleteRequest:
	//	*Delete_Interface
	DeleteRequest        isDelete_DeleteRequest `protobuf_oneof:"delete_request"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Delete) Reset()         { *m = Delete{} }
func (m *Delete) String() string { return proto.CompactTextString(m) }
func (*Delete) ProtoMessage()    {}
func (*Delete) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcbdd1ffbcbe4fbb, []int{8}
}

func (m *Delete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delete.Unmarshal(m, b)
}
func (m *Delete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delete.Marshal(b, m, deterministic)
}
func (m *Delete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delete.Merge(m, src)
}
func (m *Delete) XXX_Size() int {
	return xxx_messageInfo_Delete.Size(m)
}
func (m *Delete) XXX_DiscardUnknown() {
	xxx_messageInfo_Delete.DiscardUnknown(m)
}

var xxx_messageInfo_Delete proto.InternalMessageInfo

type isDelete_DeleteRequest interface {
	isDelete_DeleteRequest()
}

type Delete_Interface struct {
	Interface *Interface `protobuf:"bytes,1,opt,name=interface,proto3,oneof"`
}

func (*Delete_Interface) isDelete_DeleteRequest() {}

func (m *Delete) GetDeleteRequest() isDelete_DeleteRequest {
	if m != nil {
		return m.DeleteRequest
	}
	return nil
}

func (m *Delete) GetInterface() *Interface {
	if x, ok := m.GetDeleteRequest().(*Delete_Interface); ok {
		return x.Interface
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Delete) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Delete_Interface)(nil),
	}
}

func init() {
	proto.RegisterType((*Interface)(nil), "devicemanager.Interface")
	proto.RegisterType((*Device)(nil), "devicemanager.Device")
	proto.RegisterType((*Result)(nil), "devicemanager.Result")
	proto.RegisterType((*Filter)(nil), "devicemanager.Filter")
	proto.RegisterType((*Process)(nil), "devicemanager.Process")
	proto.RegisterType((*Request)(nil), "devicemanager.Request")
	proto.RegisterType((*Create)(nil), "devicemanager.Create")
	proto.RegisterType((*Interfaces)(nil), "devicemanager.Interfaces")
	proto.RegisterType((*Delete)(nil), "devicemanager.Delete")
}

func init() { proto.RegisterFile("device_manager.proto", fileDescriptor_bcbdd1ffbcbe4fbb) }

var fileDescriptor_bcbdd1ffbcbe4fbb = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x5b, 0x6b, 0x13, 0x4f,
	0x14, 0xcf, 0x36, 0xed, 0x6e, 0x72, 0xfe, 0xb4, 0x94, 0xe1, 0x5f, 0x19, 0xfb, 0x14, 0x16, 0x84,
	0xbc, 0x98, 0x0d, 0xb1, 0x04, 0xd1, 0xb7, 0x58, 0x25, 0x3e, 0x08, 0x32, 0x88, 0x82, 0x2f, 0x65,
	0xba, 0x7b, 0x4c, 0x46, 0xf7, 0xe6, 0xcc, 0xec, 0x7e, 0x54, 0x3f, 0x8f, 0xcc, 0x65, 0x37, 0x17,
	0x6d, 0xf1, 0x29, 0x73, 0xce, 0xfc, 0x2e, 0xe7, 0xfc, 0x32, 0x0b, 0xff, 0x67, 0xd8, 0x8a, 0x14,
	0xef, 0x0a, 0x5e, 0xf2, 0x0d, 0xca, 0x59, 0x2d, 0x2b, 0x5d, 0x91, 0x73, 0xd7, 0xf5, 0xcd, 0xf8,
	0x57, 0x00, 0xe3, 0xf7, 0xa5, 0x46, 0xf9, 0x8d, 0xa7, 0x48, 0x08, 0x9c, 0x96, 0xbc, 0x40, 0x1a,
	0x4c, 0x82, 0xe9, 0x98, 0xd9, 0xb3, 0xe9, 0x89, 0xba, 0xbd, 0xa1, 0x27, 0xae, 0x67, 0xce, 0xbe,
	0xb7, 0xa4, 0xc3, 0xbe, 0xb7, 0x24, 0x73, 0x08, 0x6b, 0x2e, 0xb1, 0xd4, 0xf4, 0x74, 0x12, 0x4c,
	0xff, 0x5b, 0xd0, 0xd9, 0x81, 0xd3, 0xac, 0x77, 0x61, 0x1e, 0x67, 0x54, 0x9a, 0x46, 0x64, 0xf4,
	0xcc, 0xa9, 0x98, 0x33, 0x79, 0x0e, 0xa1, 0xa3, 0xd1, 0xd0, 0xaa, 0x5c, 0x1d, 0xa9, 0xdc, 0xda,
	0x8a, 0x79, 0x10, 0xa1, 0x10, 0xb5, 0x28, 0x95, 0xa8, 0x4a, 0x1a, 0x4d, 0x82, 0xe9, 0x19, 0xeb,
	0xca, 0x78, 0x0e, 0xa1, 0xc3, 0x3e, 0xb4, 0x94, 0xb5, 0x3e, 0xd9, 0x59, 0xc7, 0xdf, 0x21, 0x64,
	0xa8, 0x9a, 0x5c, 0x93, 0x6b, 0x18, 0x49, 0x4c, 0x51, 0xb4, 0x98, 0x59, 0xd6, 0x88, 0xf5, 0xb5,
	0x71, 0xe4, 0x75, 0x9d, 0x0b, 0x74, 0xe4, 0x11, 0xeb, 0x4a, 0x72, 0x09, 0xc3, 0x42, 0x6d, 0x7c,
	0x26, 0xe6, 0x68, 0xb0, 0xaa, 0x49, 0x53, 0x54, 0xca, 0x66, 0x32, 0x62, 0x5d, 0x19, 0xbf, 0x82,
	0xf0, 0x9d, 0xc8, 0x35, 0xca, 0xbd, 0xd8, 0x82, 0x7f, 0x8b, 0x2d, 0x7e, 0x06, 0xd1, 0x47, 0x59,
	0x19, 0x19, 0x33, 0xe8, 0xb6, 0x52, 0x7a, 0x6f, 0xbd, 0xbe, 0x8e, 0x5b, 0x88, 0x18, 0xfe, 0x6c,
	0x50, 0x69, 0x92, 0x40, 0x98, 0x4a, 0xe4, 0x1a, 0xbd, 0xc7, 0x71, 0xa8, 0x6f, 0xec, 0xe5, 0x7a,
	0xc0, 0x3c, 0xcc, 0x10, 0x32, 0xcc, 0x51, 0xa3, 0xdd, 0xf1, 0x6f, 0xff, 0x82, 0xb9, 0x34, 0x04,
	0x07, 0x5b, 0x8d, 0x21, 0x92, 0xce, 0x2c, 0xfe, 0x02, 0xa1, 0xd3, 0x23, 0xaf, 0x01, 0x44, 0x37,
	0xbd, 0xf2, 0xd6, 0x4f, 0x1f, 0x5a, 0x4f, 0xad, 0x07, 0x6c, 0x0f, 0xbe, 0xba, 0x84, 0x0b, 0x37,
	0xcc, 0x5d, 0x27, 0x7c, 0x0b, 0xb0, 0x43, 0x93, 0x25, 0x8c, 0x7b, 0x34, 0x0d, 0x26, 0xc3, 0x47,
	0xa3, 0xdb, 0x41, 0xe3, 0x4f, 0xe6, 0x5d, 0x98, 0x99, 0xc9, 0xcb, 0x43, 0x85, 0x47, 0xc3, 0x5f,
	0x0f, 0xf6, 0x34, 0xcc, 0x6c, 0x6e, 0xef, 0x6e, 0xb6, 0xc5, 0x67, 0x38, 0x77, 0xaf, 0xed, 0x83,
	0x63, 0x92, 0xb7, 0x70, 0xe1, 0xd3, 0x5f, 0xf3, 0x32, 0xcb, 0x51, 0x92, 0x27, 0x47, 0xda, 0xfe,
	0xfa, 0xfa, 0xea, 0x8f, 0xbe, 0x79, 0x83, 0xf1, 0x60, 0x1a, 0xcc, 0x83, 0xd5, 0xcd, 0xd7, 0xc5,
	0x46, 0xe8, 0x6d, 0x73, 0x3f, 0x4b, 0xab, 0x22, 0x29, 0x44, 0xba, 0xe5, 0x98, 0x6f, 0xb1, 0xfc,
	0x81, 0x79, 0x92, 0x15, 0xe5, 0x26, 0x39, 0xe0, 0x26, 0xf6, 0x13, 0x57, 0xf7, 0xa1, 0xfd, 0x7d,
	0xf1, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xc2, 0xb8, 0xa5, 0x02, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DeviceManagerClient is the client API for DeviceManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeviceManagerClient interface {
	RequestHandler(ctx context.Context, opts ...grpc.CallOption) (DeviceManager_RequestHandlerClient, error)
}

type deviceManagerClient struct {
	cc *grpc.ClientConn
}

func NewDeviceManagerClient(cc *grpc.ClientConn) DeviceManagerClient {
	return &deviceManagerClient{cc}
}

func (c *deviceManagerClient) RequestHandler(ctx context.Context, opts ...grpc.CallOption) (DeviceManager_RequestHandlerClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DeviceManager_serviceDesc.Streams[0], "/devicemanager.DeviceManager/RequestHandler", opts...)
	if err != nil {
		return nil, err
	}
	x := &deviceManagerRequestHandlerClient{stream}
	return x, nil
}

type DeviceManager_RequestHandlerClient interface {
	Send(*Request) error
	Recv() (*Result, error)
	grpc.ClientStream
}

type deviceManagerRequestHandlerClient struct {
	grpc.ClientStream
}

func (x *deviceManagerRequestHandlerClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *deviceManagerRequestHandlerClient) Recv() (*Result, error) {
	m := new(Result)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DeviceManagerServer is the server API for DeviceManager service.
type DeviceManagerServer interface {
	RequestHandler(DeviceManager_RequestHandlerServer) error
}

// UnimplementedDeviceManagerServer can be embedded to have forward compatible implementations.
type UnimplementedDeviceManagerServer struct {
}

func (*UnimplementedDeviceManagerServer) RequestHandler(srv DeviceManager_RequestHandlerServer) error {
	return status.Errorf(codes.Unimplemented, "method RequestHandler not implemented")
}

func RegisterDeviceManagerServer(s *grpc.Server, srv DeviceManagerServer) {
	s.RegisterService(&_DeviceManager_serviceDesc, srv)
}

func _DeviceManager_RequestHandler_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DeviceManagerServer).RequestHandler(&deviceManagerRequestHandlerServer{stream})
}

type DeviceManager_RequestHandlerServer interface {
	Send(*Result) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type deviceManagerRequestHandlerServer struct {
	grpc.ServerStream
}

func (x *deviceManagerRequestHandlerServer) Send(m *Result) error {
	return x.ServerStream.SendMsg(m)
}

func (x *deviceManagerRequestHandlerServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _DeviceManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "devicemanager.DeviceManager",
	HandlerType: (*DeviceManagerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RequestHandler",
			Handler:       _DeviceManager_RequestHandler_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "device_manager.proto",
}
