// Code generated by protoc-gen-go. DO NOT EDIT.
// source: device_manager.proto

package devicemanager

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Interface struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ipv4                 string     `protobuf:"bytes,2,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6                 string     `protobuf:"bytes,3,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	Parent               *Interface `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
	Uuid                 string     `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Interface) Reset()         { *m = Interface{} }
func (m *Interface) String() string { return proto.CompactTextString(m) }
func (*Interface) ProtoMessage()    {}
func (*Interface) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcbdd1ffbcbe4fbb, []int{0}
}

func (m *Interface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interface.Unmarshal(m, b)
}
func (m *Interface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interface.Marshal(b, m, deterministic)
}
func (m *Interface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interface.Merge(m, src)
}
func (m *Interface) XXX_Size() int {
	return xxx_messageInfo_Interface.Size(m)
}
func (m *Interface) XXX_DiscardUnknown() {
	xxx_messageInfo_Interface.DiscardUnknown(m)
}

var xxx_messageInfo_Interface proto.InternalMessageInfo

func (m *Interface) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Interface) GetIpv4() string {
	if m != nil {
		return m.Ipv4
	}
	return ""
}

func (m *Interface) GetIpv6() string {
	if m != nil {
		return m.Ipv6
	}
	return ""
}

func (m *Interface) GetParent() *Interface {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *Interface) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type Result struct {
	Received             bool     `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	Applied              bool     `protobuf:"varint,2,opt,name=applied,proto3" json:"applied,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcbdd1ffbcbe4fbb, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetReceived() bool {
	if m != nil {
		return m.Received
	}
	return false
}

func (m *Result) GetApplied() bool {
	if m != nil {
		return m.Applied
	}
	return false
}

func (m *Result) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Filter struct {
	Parent               *Interface `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcbdd1ffbcbe4fbb, []int{2}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetParent() *Interface {
	if m != nil {
		return m.Parent
	}
	return nil
}

func init() {
	proto.RegisterType((*Interface)(nil), "devicemanager.Interface")
	proto.RegisterType((*Result)(nil), "devicemanager.Result")
	proto.RegisterType((*Filter)(nil), "devicemanager.Filter")
}

func init() { proto.RegisterFile("device_manager.proto", fileDescriptor_bcbdd1ffbcbe4fbb) }

var fileDescriptor_bcbdd1ffbcbe4fbb = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xc1, 0x4a, 0xf3, 0x40,
	0x14, 0x85, 0xff, 0xb4, 0xfd, 0x63, 0x7b, 0xb5, 0x2a, 0x83, 0xc2, 0xd0, 0x55, 0xc9, 0xaa, 0xab,
	0xa4, 0x54, 0xe9, 0xc2, 0x95, 0xd4, 0x5a, 0x11, 0x14, 0x24, 0x4b, 0x37, 0x32, 0x4d, 0xae, 0xe9,
	0x60, 0x66, 0x1a, 0x26, 0x93, 0xbe, 0x85, 0x6f, 0xe2, 0x43, 0x4a, 0x66, 0xd2, 0xd6, 0x14, 0x2a,
	0x05, 0x77, 0xe7, 0x7e, 0x39, 0x39, 0xf7, 0x70, 0x19, 0xb8, 0x88, 0x71, 0xc5, 0x23, 0x7c, 0x13,
	0x4c, 0xb2, 0x04, 0x95, 0x9f, 0xa9, 0xa5, 0x5e, 0x92, 0xae, 0xa5, 0x15, 0xf4, 0x3e, 0x1d, 0xe8,
	0x3c, 0x4a, 0x8d, 0xea, 0x9d, 0x45, 0x48, 0x08, 0xb4, 0x24, 0x13, 0x48, 0x9d, 0xbe, 0x33, 0xe8,
	0x84, 0x46, 0x97, 0x8c, 0x67, 0xab, 0x6b, 0xda, 0xb0, 0xac, 0xd4, 0x15, 0x1b, 0xd3, 0xe6, 0x86,
	0x8d, 0xc9, 0x10, 0xdc, 0x8c, 0x29, 0x94, 0x9a, 0xb6, 0xfa, 0xce, 0xe0, 0x78, 0x44, 0xfd, 0xda,
	0x26, 0x7f, 0xb3, 0x25, 0xac, 0x7c, 0x65, 0x4a, 0x51, 0xf0, 0x98, 0xfe, 0xb7, 0x29, 0xa5, 0xf6,
	0x5e, 0xc0, 0x0d, 0x31, 0x2f, 0x52, 0x4d, 0x7a, 0xd0, 0x56, 0x18, 0x21, 0x5f, 0x61, 0x6c, 0xfa,
	0xb4, 0xc3, 0xcd, 0x4c, 0x28, 0x1c, 0xb1, 0x2c, 0x4b, 0x39, 0xc6, 0xa6, 0x56, 0x3b, 0x5c, 0x8f,
	0xe4, 0x1c, 0x9a, 0x22, 0x4f, 0xaa, 0x62, 0xa5, 0xf4, 0x6e, 0xc0, 0x9d, 0xf1, 0x54, 0xa3, 0xfa,
	0xd1, 0xd0, 0x39, 0xac, 0xe1, 0xe8, 0xab, 0x01, 0xdd, 0xa9, 0xf1, 0x3c, 0x5b, 0x0f, 0x99, 0xc2,
	0xc9, 0x03, 0xea, 0xed, 0xc5, 0xf6, 0x66, 0xf4, 0xf6, 0x7e, 0xf1, 0xfe, 0x91, 0x7b, 0x38, 0x7d,
	0xe2, 0xf9, 0x36, 0x26, 0x27, 0x97, 0x3b, 0x6e, 0x5b, 0xf9, 0xb7, 0x90, 0xa1, 0x43, 0x66, 0x70,
	0x76, 0xa7, 0x90, 0x69, 0x3c, 0xa4, 0xcf, 0xee, 0x06, 0x7b, 0xe6, 0x75, 0xce, 0x14, 0x53, 0xfc,
	0x6b, 0xce, 0x64, 0xf2, 0x7a, 0x9b, 0x70, 0xbd, 0x28, 0xe6, 0x7e, 0xb4, 0x14, 0x81, 0xe0, 0xd1,
	0x82, 0x61, 0xba, 0x40, 0xf9, 0x81, 0x69, 0x10, 0x0b, 0x99, 0x04, 0xb5, 0x3f, 0x03, 0xf3, 0x20,
	0xf3, 0x3a, 0x9c, 0xbb, 0x86, 0x5e, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0xed, 0xc5, 0xed, 0x79,
	0xbe, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DeviceManagerClient is the client API for DeviceManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeviceManagerClient interface {
	GetInterface(ctx context.Context, in *Interface, opts ...grpc.CallOption) (*Interface, error)
	ListInterfaces(ctx context.Context, in *Filter, opts ...grpc.CallOption) (DeviceManager_ListInterfacesClient, error)
	CreateInterface(ctx context.Context, in *Interface, opts ...grpc.CallOption) (DeviceManager_CreateInterfaceClient, error)
	DeleteInterface(ctx context.Context, in *Interface, opts ...grpc.CallOption) (DeviceManager_DeleteInterfaceClient, error)
}

type deviceManagerClient struct {
	cc *grpc.ClientConn
}

func NewDeviceManagerClient(cc *grpc.ClientConn) DeviceManagerClient {
	return &deviceManagerClient{cc}
}

func (c *deviceManagerClient) GetInterface(ctx context.Context, in *Interface, opts ...grpc.CallOption) (*Interface, error) {
	out := new(Interface)
	err := c.cc.Invoke(ctx, "/devicemanager.DeviceManager/GetInterface", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceManagerClient) ListInterfaces(ctx context.Context, in *Filter, opts ...grpc.CallOption) (DeviceManager_ListInterfacesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DeviceManager_serviceDesc.Streams[0], "/devicemanager.DeviceManager/ListInterfaces", opts...)
	if err != nil {
		return nil, err
	}
	x := &deviceManagerListInterfacesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DeviceManager_ListInterfacesClient interface {
	Recv() (*Interface, error)
	grpc.ClientStream
}

type deviceManagerListInterfacesClient struct {
	grpc.ClientStream
}

func (x *deviceManagerListInterfacesClient) Recv() (*Interface, error) {
	m := new(Interface)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *deviceManagerClient) CreateInterface(ctx context.Context, in *Interface, opts ...grpc.CallOption) (DeviceManager_CreateInterfaceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DeviceManager_serviceDesc.Streams[1], "/devicemanager.DeviceManager/CreateInterface", opts...)
	if err != nil {
		return nil, err
	}
	x := &deviceManagerCreateInterfaceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DeviceManager_CreateInterfaceClient interface {
	Recv() (*Result, error)
	grpc.ClientStream
}

type deviceManagerCreateInterfaceClient struct {
	grpc.ClientStream
}

func (x *deviceManagerCreateInterfaceClient) Recv() (*Result, error) {
	m := new(Result)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *deviceManagerClient) DeleteInterface(ctx context.Context, in *Interface, opts ...grpc.CallOption) (DeviceManager_DeleteInterfaceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DeviceManager_serviceDesc.Streams[2], "/devicemanager.DeviceManager/DeleteInterface", opts...)
	if err != nil {
		return nil, err
	}
	x := &deviceManagerDeleteInterfaceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DeviceManager_DeleteInterfaceClient interface {
	Recv() (*Result, error)
	grpc.ClientStream
}

type deviceManagerDeleteInterfaceClient struct {
	grpc.ClientStream
}

func (x *deviceManagerDeleteInterfaceClient) Recv() (*Result, error) {
	m := new(Result)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DeviceManagerServer is the server API for DeviceManager service.
type DeviceManagerServer interface {
	GetInterface(context.Context, *Interface) (*Interface, error)
	ListInterfaces(*Filter, DeviceManager_ListInterfacesServer) error
	CreateInterface(*Interface, DeviceManager_CreateInterfaceServer) error
	DeleteInterface(*Interface, DeviceManager_DeleteInterfaceServer) error
}

// UnimplementedDeviceManagerServer can be embedded to have forward compatible implementations.
type UnimplementedDeviceManagerServer struct {
}

func (*UnimplementedDeviceManagerServer) GetInterface(ctx context.Context, req *Interface) (*Interface, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInterface not implemented")
}
func (*UnimplementedDeviceManagerServer) ListInterfaces(req *Filter, srv DeviceManager_ListInterfacesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListInterfaces not implemented")
}
func (*UnimplementedDeviceManagerServer) CreateInterface(req *Interface, srv DeviceManager_CreateInterfaceServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateInterface not implemented")
}
func (*UnimplementedDeviceManagerServer) DeleteInterface(req *Interface, srv DeviceManager_DeleteInterfaceServer) error {
	return status.Errorf(codes.Unimplemented, "method DeleteInterface not implemented")
}

func RegisterDeviceManagerServer(s *grpc.Server, srv DeviceManagerServer) {
	s.RegisterService(&_DeviceManager_serviceDesc, srv)
}

func _DeviceManager_GetInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Interface)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceManagerServer).GetInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devicemanager.DeviceManager/GetInterface",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceManagerServer).GetInterface(ctx, req.(*Interface))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceManager_ListInterfaces_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Filter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeviceManagerServer).ListInterfaces(m, &deviceManagerListInterfacesServer{stream})
}

type DeviceManager_ListInterfacesServer interface {
	Send(*Interface) error
	grpc.ServerStream
}

type deviceManagerListInterfacesServer struct {
	grpc.ServerStream
}

func (x *deviceManagerListInterfacesServer) Send(m *Interface) error {
	return x.ServerStream.SendMsg(m)
}

func _DeviceManager_CreateInterface_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Interface)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeviceManagerServer).CreateInterface(m, &deviceManagerCreateInterfaceServer{stream})
}

type DeviceManager_CreateInterfaceServer interface {
	Send(*Result) error
	grpc.ServerStream
}

type deviceManagerCreateInterfaceServer struct {
	grpc.ServerStream
}

func (x *deviceManagerCreateInterfaceServer) Send(m *Result) error {
	return x.ServerStream.SendMsg(m)
}

func _DeviceManager_DeleteInterface_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Interface)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeviceManagerServer).DeleteInterface(m, &deviceManagerDeleteInterfaceServer{stream})
}

type DeviceManager_DeleteInterfaceServer interface {
	Send(*Result) error
	grpc.ServerStream
}

type deviceManagerDeleteInterfaceServer struct {
	grpc.ServerStream
}

func (x *deviceManagerDeleteInterfaceServer) Send(m *Result) error {
	return x.ServerStream.SendMsg(m)
}

var _DeviceManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "devicemanager.DeviceManager",
	HandlerType: (*DeviceManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInterface",
			Handler:    _DeviceManager_GetInterface_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListInterfaces",
			Handler:       _DeviceManager_ListInterfaces_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CreateInterface",
			Handler:       _DeviceManager_CreateInterface_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DeleteInterface",
			Handler:       _DeviceManager_DeleteInterface_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "device_manager.proto",
}
