// Code generated by protoc-gen-go. DO NOT EDIT.
// source: device_manager.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Interface struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ipv4                 string     `protobuf:"bytes,2,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6                 string     `protobuf:"bytes,3,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	Parent               *Interface `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
	Uuid                 string     `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Interface) Reset()         { *m = Interface{} }
func (m *Interface) String() string { return proto.CompactTextString(m) }
func (*Interface) ProtoMessage()    {}
func (*Interface) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcbdd1ffbcbe4fbb, []int{0}
}

func (m *Interface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interface.Unmarshal(m, b)
}
func (m *Interface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interface.Marshal(b, m, deterministic)
}
func (m *Interface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interface.Merge(m, src)
}
func (m *Interface) XXX_Size() int {
	return xxx_messageInfo_Interface.Size(m)
}
func (m *Interface) XXX_DiscardUnknown() {
	xxx_messageInfo_Interface.DiscardUnknown(m)
}

var xxx_messageInfo_Interface proto.InternalMessageInfo

func (m *Interface) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Interface) GetIpv4() string {
	if m != nil {
		return m.Ipv4
	}
	return ""
}

func (m *Interface) GetIpv6() string {
	if m != nil {
		return m.Ipv6
	}
	return ""
}

func (m *Interface) GetParent() *Interface {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *Interface) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type Result struct {
	Received             bool     `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	Applied              bool     `protobuf:"varint,2,opt,name=applied,proto3" json:"applied,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcbdd1ffbcbe4fbb, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetReceived() bool {
	if m != nil {
		return m.Received
	}
	return false
}

func (m *Result) GetApplied() bool {
	if m != nil {
		return m.Applied
	}
	return false
}

func (m *Result) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Filter struct {
	Parent               *Interface `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcbdd1ffbcbe4fbb, []int{2}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetParent() *Interface {
	if m != nil {
		return m.Parent
	}
	return nil
}

func init() {
	proto.RegisterType((*Interface)(nil), "devicemanager.Interface")
	proto.RegisterType((*Result)(nil), "devicemanager.Result")
	proto.RegisterType((*Filter)(nil), "devicemanager.Filter")
}

func init() { proto.RegisterFile("device_manager.proto", fileDescriptor_bcbdd1ffbcbe4fbb) }

var fileDescriptor_bcbdd1ffbcbe4fbb = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x41, 0x4f, 0xc2, 0x40,
	0x10, 0x85, 0x2d, 0x60, 0x85, 0x51, 0xd4, 0x6c, 0x34, 0xd9, 0x70, 0x22, 0x3d, 0x71, 0x6a, 0x09,
	0x12, 0x0e, 0x1e, 0x15, 0x31, 0x26, 0x9a, 0x98, 0x1e, 0xbd, 0x98, 0xa5, 0x1d, 0xcb, 0xc6, 0xee,
	0xd2, 0x6c, 0xb7, 0xfc, 0x0b, 0xff, 0x89, 0x3f, 0xd2, 0x74, 0xb7, 0x14, 0x21, 0xc1, 0x90, 0x78,
	0xea, 0x9b, 0xd7, 0xd7, 0x37, 0x5f, 0x26, 0x85, 0xab, 0x18, 0x57, 0x3c, 0xc2, 0x77, 0xc1, 0x24,
	0x4b, 0x50, 0xf9, 0x99, 0x5a, 0xea, 0x25, 0xe9, 0x5a, 0xb7, 0x32, 0xbd, 0x2f, 0x07, 0x3a, 0x4f,
	0x52, 0xa3, 0xfa, 0x60, 0x11, 0x12, 0x02, 0x2d, 0xc9, 0x04, 0x52, 0xa7, 0xef, 0x0c, 0x3a, 0xa1,
	0xd1, 0xa5, 0xc7, 0xb3, 0xd5, 0x98, 0x36, 0xac, 0x57, 0xea, 0xca, 0x9b, 0xd0, 0x66, 0xed, 0x4d,
	0xc8, 0x10, 0xdc, 0x8c, 0x29, 0x94, 0x9a, 0xb6, 0xfa, 0xce, 0xe0, 0x74, 0x44, 0xfd, 0xad, 0x4d,
	0x7e, 0xbd, 0x25, 0xac, 0x72, 0x65, 0x4b, 0x51, 0xf0, 0x98, 0x1e, 0xdb, 0x96, 0x52, 0x7b, 0xaf,
	0xe0, 0x86, 0x98, 0x17, 0xa9, 0x26, 0x3d, 0x68, 0x2b, 0x8c, 0x90, 0xaf, 0x30, 0x36, 0x3c, 0xed,
	0xb0, 0x9e, 0x09, 0x85, 0x13, 0x96, 0x65, 0x29, 0xc7, 0xd8, 0x60, 0xb5, 0xc3, 0xf5, 0x48, 0x2e,
	0xa1, 0x29, 0xf2, 0xa4, 0x02, 0x2b, 0xa5, 0x77, 0x0b, 0xee, 0x8c, 0xa7, 0x1a, 0xd5, 0x2f, 0x42,
	0xe7, 0x30, 0xc2, 0xd1, 0x77, 0x03, 0xba, 0x53, 0x93, 0x79, 0xb1, 0x19, 0x32, 0x85, 0xb3, 0x47,
	0xd4, 0x9b, 0x8b, 0xed, 0xed, 0xe8, 0xed, 0x7d, 0xe3, 0x1d, 0x91, 0x07, 0x38, 0x7f, 0xe6, 0xf9,
	0xa6, 0x26, 0x27, 0xd7, 0x3b, 0x69, 0x8b, 0xfc, 0x57, 0xc9, 0xd0, 0x21, 0x33, 0xb8, 0xb8, 0x57,
	0xc8, 0x34, 0x1e, 0xc2, 0xb3, 0xbb, 0xc1, 0x9e, 0x79, 0xdd, 0x33, 0xc5, 0x14, 0xff, 0xdb, 0x73,
	0x37, 0x7e, 0x1b, 0x25, 0x5c, 0x2f, 0x8a, 0xb9, 0x1f, 0x2d, 0x45, 0x20, 0x78, 0xb4, 0x60, 0x98,
	0x2e, 0x50, 0x7e, 0x62, 0x1a, 0xc4, 0x42, 0x26, 0xc1, 0xd6, 0x97, 0x81, 0xf9, 0x21, 0xf3, 0xb9,
	0x6b, 0x9e, 0x37, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x16, 0x6a, 0xb4, 0xde, 0xb0, 0x02, 0x00,
	0x00,
}
